language: go
go:
  - 1.8

# Don't build other branches that are being used for PRs.
# Currently only the master branch is used in this repo.
branches:
  only:
    - master

cache:
  directories:
    - $GOPATH/src
    - $GOPATH/pkg

before_install:
- go get github.com/mitchellh/gox
- go get -u github.com/kyoh86/richgo
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls

script:
  - go vet ./...
  - golint ./...
  - richgo test -v -cover -coverprofile=c.out
  - goveralls -coverprofile=c.out -service travis-ci -repotoken $COVERALLS_TOKEN

after_success:
  - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
